sm8250-common: Add libion to libgsl shared libs
Fixes Soong ELF check failure for libgsl.so due to missing DT_NEEDED
entry for libion.so:

  error: DT_NEEDED "libion.so" is not specified in shared_libs